local function Text(text)
	menu.add_action(text, function() end)
end
menu.add_action("Add Badsport", function()
	stats.set_int("MPPLY_BADSPORT_MESSAGE", -1)
	stats.set_int("MPPLY_BECAME_BADSPORT_NUM", -1)
	stats.set_float("MPPLY_OVERALL_BADSPORT", 60000)
	stats.set_bool("MPPLY_CHAR_IS_BADSPORT", true)
end)
menu.add_action("Remove Badsport", function()
	stats.set_int("MPPLY_BADSPORT_MESSAGE", 0)
	stats.set_int("MPPLY_BECAME_BADSPORT_NUM", 0)
	stats.set_float("MPPLY_OVERALL_BADSPORT", 0)
	stats.set_bool("MPPLY_CHAR_IS_BADSPORT", false)
end)
Text("-----------------> Killa B <-------------------")
