local coll_menu = menu.add_submenu("Collectibles")

 local function Text(text)
	coll_menu:add_action(text, function() end)
end
Text("--------------------------------------------")
Text("COLLECTIBLES")
Text("--")
local tutcol_menu = coll_menu:add_submenu("Tutorial")
local function Text2(text)
	tutcol_menu:add_action(text, function() end)
end
Text2("--CATCH THEM ALL!--")
Text2(">>Action-Figures")
Text2("Set the Action Figure Function on 99")
Text2("Then collect the last one  and ur done")
Text2(">>Playing Cards")
Text2("Set the Action Figure Function on 53")
Text2("Then collect the last one  and ur done")
Text2(">>Singal Jammers")
Text2("Set the Action Figure Function on 49")
Text2("Then collect the last one  and ur done")
Text2(">>Shipwrecks")
Text2("Set the Action Figure Function on 29")
Text2("Then collect the last one and ur done")
Text("--")
coll_menu:add_int_range("Action Figures", 1, 1, 99, function() 
	return globals.get_int(2784215)
end, function(value)
	globals.set_int(2784215, value)
end)
coll_menu:add_int_range("Playing Cards", 1, 1, 53, function() 
	return globals.get_int(2784216)
end, function(value)
	globals.set_int(2784216, value)
end)
coll_menu:add_int_range("Signal Jammers", 1, 1, 49, function() 
	return globals.get_int(2784217)
end, function(value)
	globals.set_int(2784217, value)
end)
coll_menu:add_int_range("Shipwrecks", 1, 1, 29, function() 
	return globals.get_int(2784552)
end, function(value)
	globals.set_int(2784552, value)
end)
Text("--")
Text("➫ΞΛZТΞΛ#3171/SLON")
Text("--------------------------------------------")