local function Text(text)
	menu.add_action(text,  function() end)
end
Text("                      ~K/D Editor~  ")
menu.add_int_range("Kills", 10, 0, 999999, function()
	return stats.get_int("MPPLY_KILLS_PLAYERS")
end, function(value)
	stats.set_int("MPPLY_KILLS_PLAYERS", value)
end)
menu.add_int_range("Deaths", 10, 0, 999999, function()
	return stats.get_int("MPPLY_DEATHS_PLAYER")
end, function(value)
	stats.set_int("MPPLY_DEATHS_PLAYER", value)
end)
menu.add_float_range("K/D Ratio", 0.01, 0, 9999, function()
	return stats.get_float("MPPLY_KILL_DEATH_RATIO")
end, function(value)
	stats.set_float("MPPLY_KILL_DEATH_RATIO", value)
end)
Text("-----------------> Killa B <-------------------")