local function UnlockALLTatoos()
	mpx = "MP0_"
	mpIndex = globals.get_int(1574907)
	if mpIndex == 1 then
		mpx = "MP1_"
	end
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_0", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_1", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_2", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_3", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_4", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_5", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_6", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_7", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_8", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_9", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_10", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_11", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_12", -1)
        stats.set_int(mpx.."TATTOO_FM_UNLOCKS_13", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_14", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_15", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_16", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_17", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_18", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_19", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_20", -1)
        stats.set_int(mpx.."TATTOO_FM_UNLOCKS_21", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_22", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_23", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_24", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_25", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_26", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_27", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_28", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_29", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_30", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_31", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_32", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_33", -1)
        stats.set_int(mpx.."TATTOO_FM_UNLOCKS_34", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_35", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_36", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_37", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_38", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_39", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_40", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_41", -1)
        stats.set_int(mpx.."TATTOO_FM_UNLOCKS_42", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_43", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_44", -1)
        stats.set_int(mpx.."TATTOO_FM_UNLOCKS_45", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_46", -1)
	stats.set_int(mpx.."TATTOO_FM_UNLOCKS_47", -1)
	end
 
menu.add_action("UnlockALLTatoos", function()
	UnlockALLTatoos()
end)